name: 'test001'
version: '1.0.0'
config-version: 2

profile: 'test001'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

seeds:
  test001:
    +enabled: true
    +quote_columns: false

models:
  test001:
    +materialized: table